# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact_recommender.Artifact')),
                ('scope', models.CharField(max_length=20)),
                ('min_age', models.IntegerField(null=True)),
            ],
            bases=('artifact_recommender.artifact',),
        ),
        migrations.CreateModel(
            name='BuildingBlock',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact_recommender.Artifact')),
            ],
            bases=('artifact_recommender.artifact',),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact_recommender.Artifact')),
            ],
            bases=('artifact_recommender.artifact',),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifact_recommender.Artifact')),
            ],
            bases=('artifact_recommender.artifact',),
        ),
        migrations.AddField(
            model_name='similarity',
            name='source_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_artifact', to='artifact_recommender.Artifact'),
        ),
        migrations.AddField(
            model_name='similarity',
            name='target_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_artifact', to='artifact_recommender.Artifact'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='tags',
            field=models.ManyToManyField(to='artifact_recommender.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='similarity',
            unique_together=set([('source_artifact', 'target_artifact')]),
        ),
    ]
