# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
