# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifact_recommender', '0002_auto_20170424_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lon',
        ),
    ]
